2020-09-20T12:56:27.863815+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-09-20T12:56:27.863815+00:00 app[web.1]: worker.init_process()
2020-09-20T12:56:27.863816+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
2020-09-20T12:56:27.863816+00:00 app[web.1]: self.load_wsgi()
2020-09-20T12:56:27.863816+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2020-09-20T12:56:27.863816+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2020-09-20T12:56:27.863816+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-09-20T12:56:27.863817+00:00 app[web.1]: self.callable = self.load()
2020-09-20T12:56:27.863817+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2020-09-20T12:56:27.863817+00:00 app[web.1]: return self.load_wsgiapp()
2020-09-20T12:56:27.863817+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2020-09-20T12:56:27.863817+00:00 app[web.1]: return util.import_app(self.app_uri)
2020-09-20T12:56:27.863818+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
2020-09-20T12:56:27.863818+00:00 app[web.1]: mod = importlib.import_module(module)
2020-09-20T12:56:27.863818+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-09-20T12:56:27.863818+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2020-09-20T12:56:27.863819+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-09-20T12:56:27.863819+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-09-20T12:56:27.863819+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2020-09-20T12:56:27.863819+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2020-09-20T12:56:27.863820+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2020-09-20T12:56:27.863820+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-09-20T12:56:27.863820+00:00 app[web.1]: File "/app/Django_task_app/wsgi.py", line 12, in <module>
2020-09-20T12:56:27.863820+00:00 app[web.1]: from django.core.wsgi import get_wsgi_application
2020-09-20T12:56:27.863821+00:00 app[web.1]: ModuleNotFoundError: No module named 'django'
2020-09-20T12:56:27.863911+00:00 app[web.1]: [2020-09-20 12:56:27 +0000] [9] [INFO] Worker exiting (pid: 9)
2020-09-20T12:56:27.890584+00:00 app[web.1]: [2020-09-20 12:56:27 +0000] [4] [INFO] Shutting down: Master
2020-09-20T12:56:27.890704+00:00 app[web.1]: [2020-09-20 12:56:27 +0000] [4] [INFO] Reason: Worker failed to boot.
2020-09-20T12:56:27.952907+00:00 heroku[web.1]: Process exited with status 3
2020-09-20T12:56:27.987304+00:00 heroku[web.1]: State changed from starting to crashed
2020-09-20T12:56:27.989524+00:00 heroku[web.1]: State changed from crashed to starting
2020-09-20T12:56:31.000000+00:00 app[api]: Build succeeded
2020-09-20T12:56:32.168110+00:00 heroku[web.1]: Starting process with command `gunicorn Django_task_app.wsgi --log-file -`
2020-09-20T12:56:34.464799+00:00 app[web.1]: [2020-09-20 12:56:34 +0000] [4] [INFO] Starting gunicorn 20.0.4
2020-09-20T12:56:34.465605+00:00 app[web.1]: [2020-09-20 12:56:34 +0000] [4] [INFO] Listening at: http://0.0.0.0:59042 (4)
2020-09-20T12:56:34.465764+00:00 app[web.1]: [2020-09-20 12:56:34 +0000] [4] [INFO] Using worker: sync
2020-09-20T12:56:34.475489+00:00 app[web.1]: [2020-09-20 12:56:34 +0000] [9] [INFO] Booting worker with pid: 9
2020-09-20T12:56:34.481384+00:00 app[web.1]: [2020-09-20 12:56:34 +0000] [10] [INFO] Booting worker with pid: 10
2020-09-20T12:56:34.487523+00:00 app[web.1]: [2020-09-20 12:56:34 +0000] [9] [ERROR] Exception in worker process
2020-09-20T12:56:34.487525+00:00 app[web.1]: Traceback (most recent call last):
2020-09-20T12:56:34.487538+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-09-20T12:56:34.487539+00:00 app[web.1]: worker.init_process()
2020-09-20T12:56:34.487539+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
2020-09-20T12:56:34.487539+00:00 app[web.1]: self.load_wsgi()
2020-09-20T12:56:34.487540+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2020-09-20T12:56:34.487540+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2020-09-20T12:56:34.487541+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-09-20T12:56:34.487541+00:00 app[web.1]: self.callable = self.load()
2020-09-20T12:56:34.487542+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2020-09-20T12:56:34.487542+00:00 app[web.1]: return self.load_wsgiapp()
2020-09-20T12:56:34.487542+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2020-09-20T12:56:34.487543+00:00 app[web.1]: return util.import_app(self.app_uri)
2020-09-20T12:56:34.487543+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
2020-09-20T12:56:34.487543+00:00 app[web.1]: mod = importlib.import_module(module)
2020-09-20T12:56:34.487544+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-09-20T12:56:34.487544+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2020-09-20T12:56:34.487545+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-09-20T12:56:34.487545+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-09-20T12:56:34.487545+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2020-09-20T12:56:34.487546+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2020-09-20T12:56:34.487546+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2020-09-20T12:56:34.487547+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-09-20T12:56:34.487547+00:00 app[web.1]: File "/app/Django_task_app/wsgi.py", line 12, in <module>
2020-09-20T12:56:34.487547+00:00 app[web.1]: from django.core.wsgi import get_wsgi_application
2020-09-20T12:56:34.487548+00:00 app[web.1]: ModuleNotFoundError: No module named 'django'
2020-09-20T12:56:34.487763+00:00 app[web.1]: [2020-09-20 12:56:34 +0000] [9] [INFO] Worker exiting (pid: 9)
2020-09-20T12:56:34.493979+00:00 app[web.1]: [2020-09-20 12:56:34 +0000] [10] [ERROR] Exception in worker process
2020-09-20T12:56:34.493981+00:00 app[web.1]: Traceback (most recent call last):
2020-09-20T12:56:34.493982+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-09-20T12:56:34.493982+00:00 app[web.1]: worker.init_process()
2020-09-20T12:56:34.493983+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
2020-09-20T12:56:34.493983+00:00 app[web.1]: self.load_wsgi()
2020-09-20T12:56:34.493984+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2020-09-20T12:56:34.493989+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2020-09-20T12:56:34.493990+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-09-20T12:56:34.493990+00:00 app[web.1]: self.callable = self.load()
2020-09-20T12:56:34.493991+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2020-09-20T12:56:34.493991+00:00 app[web.1]: return self.load_wsgiapp()
2020-09-20T12:56:34.493991+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2020-09-20T12:56:34.493992+00:00 app[web.1]: return util.import_app(self.app_uri)
2020-09-20T12:56:34.493992+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
2020-09-20T12:56:34.493992+00:00 app[web.1]: mod = importlib.import_module(module)
2020-09-20T12:56:34.493993+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-09-20T12:56:34.493993+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2020-09-20T12:56:34.493994+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-09-20T12:56:34.493994+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-09-20T12:56:34.493994+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2020-09-20T12:56:34.493995+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2020-09-20T12:56:34.493995+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2020-09-20T12:56:34.493995+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-09-20T12:56:34.493996+00:00 app[web.1]: File "/app/Django_task_app/wsgi.py", line 12, in <module>
2020-09-20T12:56:34.493996+00:00 app[web.1]: from django.core.wsgi import get_wsgi_application
2020-09-20T12:56:34.493997+00:00 app[web.1]: ModuleNotFoundError: No module named 'django'
2020-09-20T12:56:34.494121+00:00 app[web.1]: [2020-09-20 12:56:34 +0000] [10] [INFO] Worker exiting (pid: 10)
2020-09-20T12:56:34.627205+00:00 app[web.1]: [2020-09-20 12:56:34 +0000] [4] [INFO] Shutting down: Master
2020-09-20T12:56:34.627314+00:00 app[web.1]: [2020-09-20 12:56:34 +0000] [4] [INFO] Reason: Worker failed to boot.
2020-09-20T12:56:34.698548+00:00 heroku[web.1]: Process exited with status 3
2020-09-20T12:56:34.745921+00:00 heroku[web.1]: State changed from starting to crashed
2020-09-20T12:57:38.957014+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=blooming-taiga-84091.herokuapp.com request_id=68580cfd-2af8-4ff2-911e-4440f6f3cf1b fwd="59.94.229.252" dyno= connect= service= status=503 bytes= protocol=https
2020-09-20T12:57:46.963744+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=blooming-taiga-84091.herokuapp.com request_id=64e26223-c7a8-4db8-be5e-72ca869dfc33 fwd="59.94.229.252" dyno= connect= service= status=503 bytes= protocol=https
